global:
  scrape_interval: 45s
  scrape_timeout: 30s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
      
  - job_name: 'shadow-deals'
    metrics_path: "/prometheus"
    static_configs:
      - targets: ['host.docker.internal:8080']
  
  - job_name: 'postgres'
    static_configs:
      - targets: ['host.docker.internal:9187']